services:

  torrelay:
    image: wollomatic/torrelay:0d22614d36c24a01c442d7c900f7c350f3f5bb01
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    mem_limit: 4G # adjust
    stop_grace_period: 2m
    volumes:
      - ./torrc:/etc/tor/torrc:ro
      - data:/var/lib/tor
    network_mode: host # check if you want this

volumes:
  data:
    name: torrelay
